version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: easy-auth-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: easy-auth
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 